version: 2

sources:
  - name: restaurant_gold
    schema: restaurant_gold
    tables:
      - name: business
      - name: user
      - name: review
      - name: checkin
      - name: tip
  - name: restaurant_silver
    schema: restaurant_silver
    tables:
      - name: fact_review
      - name: dim_user
      - name: dim_restaurant
